In [2]:
%matplotlib widget

from mpl_toolkits.mplot3d import Axes3D

import matplotlib.pyplot as plt
import numpy as np
import sympy as sp

In [4]:
def plane(P, N, m):
    P = np.array(P)
    N = np.array(N)
    
    d = -P.dot(N)
    xx, yy = np.meshgrid(range(-m, m+1), range(-m, m+1))

    z = (-N[0] * xx - N[1] * yy - d) * 1 / N[2]

    return (xx, yy, z)

def boundary(E1, N, er1, er2, sigma=0):
    E1 = np.array(E1)
    N = np.array(N)

    n = N / np.linalg.norm(N)
    En1 = E1.dot(n) * n
    Et1 = E1 - En1

    En2 = (er1*En1 - sigma)/er2
    Et2 = Et1
    E2 = En2 + Et2

    return E2

In [4]:
def show_plot(E1, N, er1, er2, sigma=0):
    fig = plt.figure()
    ax = plt.axes(projection="3d")
    zero = [0, 0, 0]

    E2 = boundary(E1, N, er1, er2, sigma=sigma)
    m = int(np.ceil(np.max([N, E1, E2])))

    pln = plane(zero, N, m)
    
    ax.plot_surface(*pln, color='gray', alpha=0.5)
    ax.plot(*list(zip(zero, N)), color='red')
    ax.plot(*list(zip(zero, E1)), color='blue')
    ax.plot(*list(zip(zero, E2)), color='green')

In [5]:
show_plot([1, 2, 1], [1, 0, 1], 2.1, 4)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
show_plot([1, 2, 1], [1, 0, 1], 2.1, 4, sigma=5)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
plane([0,0,0], [1, 1, 0], 2)

(array([[-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2],
        [-2, -1,  0,  1,  2]]),
 array([[-2, -2, -2, -2, -2],
        [-1, -1, -1, -1, -1],
        [ 0,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1],
        [ 2,  2,  2,  2,  2]]),
 array([[ inf,  inf,  inf,  inf,  nan],
        [ inf,  inf,  inf,  nan, -inf],
        [ inf,  inf,  nan, -inf, -inf],
        [ inf,  nan, -inf, -inf, -inf],
        [ nan, -inf, -inf, -inf, -inf]]))