In [2]:
%matplotlib inline

from mpl_toolkits.mplot3d import Axes3D

import matplotlib.pyplot as plt
import numpy as np
import sympy as sp

In [4]:
def plane(P, N, m):
    P = np.array(P)
    N = np.array(N)
    
    d = -P.dot(N)

    if N[2] != 0:
        xx, yy = np.meshgrid(range(-m, m+1), range(-m, m+1))
        zz = (-N[0] * xx - N[1] * yy - d) / N[2]
    elif N[1] != 0:
        xx, zz = np.meshgrid(range(-m, m+1), range(-m, m+1))
        yy = (-N[0] * xx - N[2] * zz - d) / N[1]
    elif N[0] != 0:
        yy, zz = np.meshgrid(range(-m, m+1), range(-m, m+1))
        zz = (-N[1] * yy - N[2] * zz - d) / N[0]

    return (xx, yy, zz)

def boundary(N, E1, er1, er2, sigma=0):
    E1 = np.array(E1)
    N = np.array(N)

    n = N / np.linalg.norm(N)
    E1n = E1.dot(n) * n
    E1t = E1 - E1n

    E2n = (er1*E1n - sigma*n)/er2
    E2t = E1t

    E2 = E2n + E2t

    return E2

In [7]:
def show_plot(E1, N, er1, er2, sigma=0):
    fig = plt.figure()
    ax = plt.axes(projection="3d")
    zero = [0, 0, 0]

    E2 = boundary(E1, N, er1, er2, sigma=sigma)
    m = int(np.ceil(np.max([N, E1, E2])))

    pln = plane(zero, N, m)
    
    ax.plot_surface(*pln, color='gray', alpha=0.5)
    ax.plot(*list(zip(zero, N)), color='red')
    ax.plot(*list(zip(zero, E1)), color='blue')
    ax.plot(*list(zip(zero, E2)), color='green')

In [4]:
for N in ([1, 1, -1], [1, 2, 3], [-2, -4, -6], [-1, 2, 3], [1, -2, 3]):
    print(boundary(N, [1, 2, 3], 1, 2)) 

[1. 2. 3.]
[0.5 1.  1.5]
[0.5 1.  1.5]
[1.42857143 1.14285714 1.71428571]
[0.78571429 2.42857143 2.35714286]


In [14]:
boundary([1, 2, 3], [1, 1, -1], 1, 2)

array([1., 2., 3.])

In [15]:
boundary([1, 2, 3], [1, 2, 3], 1, 2)

array([0.5, 1. , 1.5])

In [16]:
boundary([1, 2, 3], [-1, -2, -3], 1, 2)

array([0.5, 1. , 1.5])

In [17]:
boundary([1, 2, 3], [1, 2, 3], 1, 2)

array([2., 4., 6.])

In [11]:
boundary([1, 2, 3], [1, 2, 3], 1, 2)

array([0.5, 1. , 1.5])

In [14]:
boundary([-1, -2, -3], [1, 2, 3], 1, 2)

array([0.5, 1. , 1.5])

In [15]:
boundary([1, 2, 3], [1, 2, 3], 1, 2, sigma=5)

array([-0.1681531 , -0.33630621, -0.50445931])

In [16]:
boundary([-1, -2, -3], [1, 2, 3], 1, 2, sigma=5)

array([1.1681531 , 2.33630621, 3.50445931])